version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports: 
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./client/.env.production

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    env_file:
      - ./server/.env.production



    