version: '3'
services:
  frontend:
    build: ./client
    ports: 
      - "5173:4173"
    depends_on:
      - backend
    env_file:
      - ./client/.env

  backend:
    build: ./server
    ports:
      - "5001:3000"
    env_file:
      - ./server/.env



    